INSERT INTO `T_MAN_TASK_CONFIG` VALUES (1, NULL, 0, NULL, '创建任务', 0);
INSERT INTO `T_MAN_TASK_CONFIG` VALUES (2, NULL, 0, NULL, '开始任务', 1);
INSERT INTO `T_MAN_TASK_CONFIG` VALUES (3, NULL, 0, NULL, '驳回任务', 2);
INSERT INTO `T_MAN_TASK_CONFIG` VALUES (4, NULL, 0, NULL, '完成任务', 3);
INSERT INTO `T_MAN_TASK_CONFIG` VALUES (5, NULL, 0, NULL, '搁置任务', 4);
INSERT INTO `T_MAN_TASK_CONFIG` VALUES (6, NULL, 0, NULL, '关闭任务', 5);
