package phasethree;

import java.awt.Color;  
import java.awt.Image;  
import java.awt.Toolkit;  
import java.awt.event.KeyAdapter;  
import java.awt.event.KeyEvent;  
import javax.swing.JOptionPane;  
  
/** 
 * 
 * @author Administrator 
 */  
public class Test extends javax.swing.JFrame  
{  
  
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	//double BANK_YEAR = 5.19;  
    private static final String[] bankLL = { //银行利率  
        "5.65","5.9", "6.15", "6.55", "6.8","7.05","7.3","7.55","5.4","5.15","4.9","4.65","4.4","4.15"  
    };  
  
    private static final String[] daze = {  
        "1.3倍", "1.2倍", "1.1倍", "无折扣", "9.5折", "9折", "8.5折", "8折", "7.5折", "7折"  
    };  
  
    private static final String[] usaful = { //还款年限初始化  
        "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",  
        "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",  
        "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"  
    };  
  
    private static final String[] items = { //还款方式初始化  
        "等额本息", "等额本金"  
    };  
  
    private static final String[] qian = {  
        "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",  
        "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",  
        "21", "22", "23", "24", "25", "26", "27", "28", "29", "30",  
        "31", "32", "33", "34", "35", "36", "37", "38", "39", "40",  
        "41", "42", "43", "44", "45", "46", "47", "48", "49", "50",  
        "51", "52", "53", "54", "55", "56", "57", "58", "59", "60",  
        "61", "62", "63", "64", "65", "66", "67", "68", "69", "70",  
        "71", "72", "73", "74", "75", "76", "77", "78", "79", "80",  
        "81", "82", "83", "84", "85", "86", "87", "88", "89", "90",  
        "91", "92", "93", "94", "95", "96", "97", "98", "99", "100"  
    };  
  
    /** 
     * Creates new form Fang 
     */  
    public Test()  
    {  
        int i;  
        initComponents();  
  
        for (i = 0; i < bankLL.length; i++) {       //为选项条赋值  
            jComboBox4.addItem(bankLL[i]);  
        }  
        for (i = 0; i < daze.length; i++) {       //为选项条赋值  
            jComboBox5.addItem(daze[i]);             // jTextField5  
        }  
        for (i = 0; i < items.length; i++) {       //为选项条赋值  
            jComboBox2.addItem(items[i]);  
        }  
        for (i = 0; i < usaful.length; i++) {  
            jComboBox1.addItem(usaful[i]);  
        }  
        for (i = 0; i < qian.length; i++) {  
            jComboBox3.addItem(qian[i]);  
        }  
  
        Image img = Toolkit.getDefaultToolkit().getImage("icon/logo.jpg");  //显示标题栏的图标  
        //myFrame.setCursor(HAND_CURSOR);  
        setIconImage(img);                                      //设置标题图标  
        setLocation(320, 100);  
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);  
        jTextField1.setEditable(false);  
        jTextField2.setEditable(false);  
        jTextField3.setEditable(false);  
        jTextField5.setEditable(false);  
        jTextField5.setText(daze[3]);  
  
        jComboBox2.setSelectedIndex(0);  //设置条选框默认值为数组中的第0个元素（此为：等额本息）  
        jComboBox1.setSelectedIndex(9);  //设置条选框默认值为数组中的第9个元素（此为：10）  
        jComboBox3.setSelectedIndex(29);  //设置条选框默认值为数组中的第29个元素（此为：30）  
        jComboBox5.setSelectedIndex(3);  
  
        jButton1.setMnemonic(KeyEvent.VK_M);      //设置method按钮的快捷键为ALT+M (此method值为"开始计算")  
        jButton2.setMnemonic(KeyEvent.VK_C);  
        jButton3.setMnemonic(KeyEvent.VK_A);  
        jButton4.setMnemonic(KeyEvent.VK_X);  
  
    }  
  
    public void keyPressed(KeyEvent e)  
    {    //键按下但未抬起(释放)  
        //System.exit(0);  
    }  
  
    //@Override  
    public void keyReleased(KeyEvent e)  
    {   //键按下后抬起(释放)  
        //if(KeyEvent.VK_SHIFT == e.getKeyCode() && KeyEvent.VK_ESCAPE==e.getKeyCode()) { //不能使用  
        //if(KeyEvent.VK_SHIFT == e.getKeyCode()) {  
        //设置按CTRL+SHIFT+ALT+F12退出窗口  
        /*if (e.isShiftDown() && e.isControlDown() && e.isAltDown() && KeyEvent.VK_F12 == e.getKeyCode()) { 
         System.exit(0); 
         }*/  
    }  
  
    //@Override  
    public void keyTyped(KeyEvent e)  
    {      //键敲击(快速)  
  
    }  
  
    /** 
     * This method is called from within the constructor to 
     * initialize the form. 
     * WARNING: Do NOT modify this code. The content of this method is 
     * always regenerated by the Form Editor. 
     */  
    @SuppressWarnings("unchecked")  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents  
    private void initComponents() {  
  
        jScrollPane1 = new javax.swing.JScrollPane();  
        jTextArea1 = new javax.swing.JTextArea();  
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));  
        jLabel1 = new javax.swing.JLabel();  
        jButton1 = new javax.swing.JButton();  
        jButton2 = new javax.swing.JButton();  
        jButton3 = new javax.swing.JButton();  
        jButton4 = new javax.swing.JButton();  
        jComboBox1 = new javax.swing.JComboBox();  
        jComboBox2 = new javax.swing.JComboBox();  
        jComboBox3 = new javax.swing.JComboBox();  
        jLabel2 = new javax.swing.JLabel();  
        jLabel3 = new javax.swing.JLabel();  
        jLabel4 = new javax.swing.JLabel();  
        jLabel5 = new javax.swing.JLabel();  
        jTextField1 = new javax.swing.JTextField();  
        jTextField2 = new javax.swing.JTextField();  
        jTextField3 = new javax.swing.JTextField();  
        jSeparator1 = new javax.swing.JSeparator();  
        jSeparator2 = new javax.swing.JSeparator();  
        jTextField4 = new javax.swing.JTextField();  
        jComboBox4 = new javax.swing.JComboBox();  
        jLabel6 = new javax.swing.JLabel();  
        jLabel7 = new javax.swing.JLabel();  
        jSeparator3 = new javax.swing.JSeparator();  
        jLabel8 = new javax.swing.JLabel();  
        jTextField5 = new javax.swing.JTextField();  
        jComboBox5 = new javax.swing.JComboBox();  
        jPanel1 = new javax.swing.JPanel();  
  
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);  
        setTitle("房贷计算器 v1.01");  
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));  
        setResizable(false);  
        addKeyListener(new java.awt.event.KeyAdapter() {  
            public void keyPressed(java.awt.event.KeyEvent evt) {  
                formKeyPressed(evt);  
            }  
        });  
       
        pack();  
    }// </editor-fold>//GEN-END:initComponents  
  
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed  
    {//GEN-HEADEREND:event_jButton4ActionPerformed  
        // TODO add your handling code here:  
        int yes;  
  
        //System.out.println(JOptionPane.getRootFrame());  
        //JOptionPane.showMessageDialog(null, "你好");  
        yes = JOptionPane.showConfirmDialog(null,  
                "你确认要退出吗？\n(退出需要密码.)",  
                "警告！！", JOptionPane.OK_CANCEL_OPTION);  
        //dialog.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);     // 设置对话框关闭按钮无效  
        //JOptionPane.showOptionDialog(rootPane, yes, null, yes, yes, null, items, rootPane)  
        //System.out.println("yes="+yes);  
        if (yes == 2) {             // 取消按钮的值为2，当按取消按钮时返回  
            return;  
        }  
        else if (yes == -1) {       // 关闭按钮的值为-1，当按关闭按钮时返回  
            return;  
        }  
        else if (evt.getSource().equals((Object) jButton4)) {     // the yes = 0，确认按钮的值为0，按确定按钮退出  
  
            System.exit(0);  
        }  
    }//GEN-LAST:event_jButton4ActionPerformed  
  
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed  
    {//GEN-HEADEREND:event_jButton3ActionPerformed  
        // TODO add your handling code here:  
        int yes;  
  
        yes = JOptionPane.showConfirmDialog(null,  
                "欢迎使用本软件,如果发现BUG\n 请 Email: fengdos@163.com \n本人将非常的感谢.\n",  
                "关于", JOptionPane.OK_CANCEL_OPTION);  
  
        //System.out.println("yes=" + yes);  
        if (yes == 0) {  
            return;  
        }  
  
        JOptionPane.showMessageDialog(null, "这是一个错\n误对话框", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);  
        JOptionPane.showMessageDialog(null, "这是一个内部\n信息对话框", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);  
        JOptionPane.showMessageDialog(null, "这是一个警\n告对话框", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);  
        JOptionPane.showMessageDialog(null, "这是一个询问对话框,\n你真的要退出吗？\n", "QUESTION_MESSAGE", JOptionPane.QUESTION_MESSAGE);  
    }//GEN-LAST:event_jButton3ActionPerformed  
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed  
    {//GEN-HEADEREND:event_jButton1ActionPerformed  
        // TODO add your handling code here:  
        String l;  
        String m;  
        String y;  
        float bankll;  
        int year;  
        float money;  
  
        l = jTextField4.getText();  
        /*if (l.equals("")) { 
         jTextArea1.setText("你输入的利率不能为空，请重新输入!!"); 
         jTextField4.setText(""); 
         return; 
         }*/  
        if (l.isEmpty()) {  
            jTextArea1.setText("你输入的利率不能为空，请重新输入!!");  
            return;  
        }  
        /*if (!l.matches("[1-9][.][0-9]*")) { 
         //JOptionPane.showMessageDialog(null, "你输入的利率不能上字符串，请重新输入!!"); 
         jTextArea1.setText("你输入的利率必须是伏点数，请重新输入!!"); 
         jTextField4.setText(""); 
         return; 
         } 
         else { 
         jTextField4.setText(l+".0"); 
         }*/  
  
        m = jTextField1.getText();  
        y = jTextField3.getText();  
        try {  
            bankll = Float.parseFloat(l);  
        }  
        catch (Exception e) {  
            //System.out.println(e.getMessage());  
            //System.out.println(e.getStackTrace());  
            //e.printStackTrace();  
            jTextArea1.setText("你输入的利率必须是伏点数，请重新输入!!");  
            jTextField4.setText("");  
            return;  
        }  
        /* if(bankll <3 || bankll >8) { 
         System.out.println("输入错误,请重新输入!!"); 
         jTextField4.setText(""); 
         }*/  
        year = Integer.parseInt(m);  
        money = Float.parseFloat(y);  
  
        //int money = Integer.parseInt(y);  
        getMethods(money, year, bankll);  
  
    }//GEN-LAST:event_jButton1ActionPerformed  
  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed  
    {//GEN-HEADEREND:event_jButton2ActionPerformed  
        // TODO add your handling code here:  
        //String sName = tf1.getText() + "." + tf2.getText();  
        jTextArea1.setText("");  
        jTextArea1.setCaretPosition(0);  
    }//GEN-LAST:event_jButton2ActionPerformed  
  
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField2ActionPerformed  
    {//GEN-HEADEREND:event_jTextField2ActionPerformed  
        // TODO add your handling code here:  
  
    }//GEN-LAST:event_jTextField2ActionPerformed  
  
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed  
    {//GEN-HEADEREND:event_jTextField1ActionPerformed  
        // TODO add your handling code here:  
  
    }//GEN-LAST:event_jTextField1ActionPerformed  
  
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField3ActionPerformed  
    {//GEN-HEADEREND:event_jTextField3ActionPerformed  
        // TODO add your handling code here:  
  
    }//GEN-LAST:event_jTextField3ActionPerformed  
  
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1ActionPerformed  
    {//GEN-HEADEREND:event_jComboBox1ActionPerformed  
        // TODO add your handling code here:  
        jTextField1.setText((String) jComboBox1.getSelectedItem());  
    }//GEN-LAST:event_jComboBox1ActionPerformed  
  
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox2ActionPerformed  
    {//GEN-HEADEREND:event_jComboBox2ActionPerformed  
        // TODO add your handling code here:  
        jTextField2.setText((String) jComboBox2.getSelectedItem());  
    }//GEN-LAST:event_jComboBox2ActionPerformed  
  
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox3ActionPerformed  
    {//GEN-HEADEREND:event_jComboBox3ActionPerformed  
        // TODO add your handling code here:  
        jTextField3.setText((String) jComboBox3.getSelectedItem());  
    }//GEN-LAST:event_jComboBox3ActionPerformed  
  
    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox4ActionPerformed  
    {//GEN-HEADEREND:event_jComboBox4ActionPerformed  
        // TODO add your handling code here:  
        jTextField4.setText((String) jComboBox4.getSelectedItem());  
    }//GEN-LAST:event_jComboBox4ActionPerformed  
  
    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField4ActionPerformed  
    {//GEN-HEADEREND:event_jTextField4ActionPerformed  
        // TODO add your handling code here:  
    }//GEN-LAST:event_jTextField4ActionPerformed  
  
    private void formKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyPressed  
    {//GEN-HEADEREND:event_formKeyPressed  
        // TODO add your handling code here:  
        /*if (evt.isShiftDown() && evt.isControlDown() && evt.isAltDown() && KeyEvent.VK_F12 == evt.getKeyCode()) { 
         System.exit(0); 
         }*/  
    }//GEN-LAST:event_formKeyPressed  
  
    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField5ActionPerformed  
    {//GEN-HEADEREND:event_jTextField5ActionPerformed  
        // TODO add your handling code here:  
          
    }//GEN-LAST:event_jTextField5ActionPerformed  
  
    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox5ActionPerformed  
    {//GEN-HEADEREND:event_jComboBox5ActionPerformed  
        // TODO add your handling code here:  
        jTextField5.setText((String) jComboBox5.getSelectedItem());  
    }//GEN-LAST:event_jComboBox5ActionPerformed  
  
    //开始计算的方法  
    public void getMethods(float money, int years, float bankll)  
    {  
        int tmp = 1;  
        float daze;  
  
        if (money < 1 || money > 100) {  
            jTextArea1.setText("你输入的金额不正确，请重新输入!!");  
            return;  
        }  
        else if (years < 1 || years > 30) {  
            jTextArea1.setText("你输入的还款年限不正确，请重新输入!!");  
            return;  
        }  
        else if (bankll < 3.0f || bankll > 8.0f) {  
            jTextArea1.setText("输入错误( 输入范围: 3.0 至 8.0 ),请重新输入小数!!");  
            return;  
        }  
  
        int k;  
        double YEAR_LL = 0, MOON_LL = 0, yuegong = 0, FirstCHLX = 0, CHLX = 0, CHBJ = 0, SYBJ = 0;  
        int year = years, moon = 0;  
        int i = 0, level = 0;  
        float r = money, RMB = 0f;  
  
        YEAR_LL = bankll / 100;  
        MOON_LL = YEAR_LL / 12;  
  
        RMB = r * 10000;  
        level = year * 12 + moon;  
        FirstCHLX = RMB * MOON_LL;  
  
        //"1.3倍", "1.2倍", "1.1倍", "无折扣", "9.5折", "9折", "8.5折", "8折", "7.5折", "7折"  
        tmp = jComboBox5.getSelectedIndex();  
        switch (tmp) {  
            case 0:  
                daze = 1.3f;  
                break;  
            case 1:  
                daze = 1.2f;  
                break;  
            case 2:  
                daze = 1.1f;  
                break;  
            case 3:  
                daze = 1.0f;  
                break;  
            case 4:  
                daze = .95f;  
                break;  
            case 5:  
                daze = .9f;  
                break;  
            case 6:  
                daze = .85f;  
                break;  
            case 7:  
                daze = .8f;  
                break;  
            case 8:  
                daze = .75f;  
                break;  
            case 9:  
                daze = .7f;  
                break;  
            default:  
                daze = 1.0f;  
  
        }  
  
        yuegong = (RMB * MOON_LL * Math.pow(1 + MOON_LL, year * 12 + moon)) / (Math.pow(1 + MOON_LL, year * 12 + moon) - 1) * daze;  
  
        CHLX = FirstCHLX;  
        CHBJ = yuegong - FirstCHLX;  
        SYBJ = RMB - CHBJ;  
  
        //System.out.println("首月利息：" + CHLX + "    偿还本金：" + CHBJ + "    剩余本金：" + SYBJ);  
        //System.out.println("\n第一年清单：");  
        //System.out.println("期数    偿还利息        偿还本金         剩余本金");  
        jTextArea1.setText("");   //清空上次内容以备下次显示  
        jTextArea1.setBackground(Color.white);  
        jTextArea1.setForeground(Color.darkGray);  
  
        for (k = 0; k < level; k++) {  
            jTextArea1.append(String.format("%3d\t%.2f\t%.2f\t%.2f\t%.2f\n", (k + 1), CHLX, CHBJ, yuegong, SYBJ));  
            CHLX = SYBJ * MOON_LL;  
            CHBJ = yuegong - CHLX;  
            SYBJ = SYBJ - CHBJ;  
        }  
  
        jTextArea1.setCaretPosition(0);     //显示完毕后自动回到文本首行  
        //jTextAreal.setEditable(false);      //设置禁止修改内容  
        //jTextAreal.setCursor(new   Cursor(Cursor.TEXT_CURSOR)); //设置光标不文本水标  
        //jTextAreal.setCursor(new   Cursor(Cursor.DEFAULT_CURSOR));  恢复光标  
        //jTextAreal.getCaret().setVisible(true);   //使Text区的文本光标显示  
    }  
  
    /** 
     * @param args the command line arguments 
     */  
    public static void main(String args[])  
    {  
        /* Set the Nimbus look and feel */  
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">  
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. 
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html  
         */  
        try {  
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {  
                if ("Nimbus".equals(info.getName())) {  
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());      // 设置窗口风格(安装Nimbus风格)  
                    break;  
                }  
            }  
        }  
        catch (ClassNotFoundException ex) {  
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);  
        }  
        catch (InstantiationException ex) {  
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);  
        }  
        catch (IllegalAccessException ex) {  
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);  
        }  
        catch (javax.swing.UnsupportedLookAndFeelException ex) {  
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);  
        }  
        //</editor-fold>  
  
        /* Create and display the form */  
        Test fr = new Test();  
        fr.addKeyListener(new KeyAdapter()  
        {  
            @Override  
            public void keyPressed(KeyEvent e)  
            {  
                if (KeyEvent.VK_ESCAPE == e.getKeyCode()) {  
                    System.exit(0);  
                }  
            }  
        });  
        java.awt.EventQueue.invokeLater(new Runnable()  
        {  
            public void run()  
            {  
                new Test().setVisible(true);  
            }  
        });  
    }  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables  
    private javax.swing.Box.Filler filler1;  
    private javax.swing.JButton jButton1;  
    private javax.swing.JButton jButton2;  
    private javax.swing.JButton jButton3;  
    private javax.swing.JButton jButton4;  
    private javax.swing.JComboBox jComboBox1;  
    private javax.swing.JComboBox jComboBox2;  
    private javax.swing.JComboBox jComboBox3;  
    private javax.swing.JComboBox jComboBox4;  
    private javax.swing.JComboBox jComboBox5;  
    private javax.swing.JLabel jLabel1;  
    private javax.swing.JLabel jLabel2;  
    private javax.swing.JLabel jLabel3;  
    private javax.swing.JLabel jLabel4;  
    private javax.swing.JLabel jLabel5;  
    private javax.swing.JLabel jLabel6;  
    private javax.swing.JLabel jLabel7;  
    private javax.swing.JLabel jLabel8;  
    private javax.swing.JPanel jPanel1;  
    private javax.swing.JScrollPane jScrollPane1;  
    private javax.swing.JSeparator jSeparator1;  
    private javax.swing.JSeparator jSeparator2;  
    private javax.swing.JSeparator jSeparator3;  
    private javax.swing.JTextArea jTextArea1;  
    private javax.swing.JTextField jTextField1;  
    private javax.swing.JTextField jTextField2;  
    private javax.swing.JTextField jTextField3;  
    private javax.swing.JTextField jTextField4;  
    private javax.swing.JTextField jTextField5;  
    // End of variables declaration//GEN-END:variables  
}  
